export const RBS_CONFIG_ABI = [
  {
    type: "function",
    name: "range",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "lastActive", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLastPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTargetPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMovingAverage",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "movingAverageDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "upperWall",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "price", type: "uint256" },
      { name: "capacity", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lowerWall",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "price", type: "uint256" },
      { name: "capacity", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "upperCushion",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "price", type: "uint256" },
      { name: "capacity", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lowerCushion",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "price", type: "uint256" },
      { name: "capacity", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextBeat",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operator",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reserveToken",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
] as const;
