-- The compute server's (mine/, flyai-mine.fly.dev) players and money, moved out of its SQLite file so the mining
-- process can never lock sign-in, balances, FlightPass or the games again (2026-09-29): sessions, the $FLYAI ledger,
-- withdrawals, miner earnings, monthly snapshots, stake samples, FlightPass, Fly Roulette, Fly Slots and Fly Race.
-- The jobs, miners, orders and their payment records stay in SQLite.
--
-- Own schema, not public: PostgREST serves only public, so nothing here is reachable with the anon or service keys'
-- REST API. The server connects as postgres through the pooler (MINE_PG_URL). Times are Unix milliseconds (bigint),
-- token amounts are wei as text, as they were in SQLite. Tests load this file into a local Postgres (mine/src/pgtest.ts).

create schema if not exists mine;
revoke all on schema mine from public, anon, authenticated;

-- the server's own notes: 'copied_from_sqlite' once its first start copied the SQLite tables here (src/legacy.ts)
create table mine.meta (
  key text primary key,
  value text not null
);

-- a wallet signed in once on the site
create table mine.sessions (
  token_hash text primary key,
  wallet text not null,
  created_at bigint not null,
  expires_at bigint not null
);
create index sessions_expiry on mine.sessions (expires_at);

-- every movement of a balance (a wallet, or pass:<id> for a FlightPass): deposit, fund (to an order), release (an
-- order's unspent budget back), withdraw, bet, payout, prefund, fee; charge rows record order spending and the pool.
-- ref: set on rows the mining process queued (its outbox), so a row sent twice lands once.
create table mine.ledger (
  id bigint generated by default as identity primary key,
  wallet text not null,
  order_id text,
  kind text not null check (kind in ('deposit', 'fund', 'release', 'withdraw', 'charge', 'bet', 'payout', 'prefund', 'fee')),
  amount_wei text not null,
  pool_wei text,
  month text,
  tx text,
  at bigint not null,
  ref text
);
create index ledger_by_wallet on mine.ledger (wallet, at);
create index ledger_charges on mine.ledger (month) where kind = 'charge';
create index ledger_by_order on mine.ledger (order_id) where order_id is not null;
create unique index ledger_tx on mine.ledger (tx) where tx is not null;
create unique index ledger_ref on mine.ledger (ref) where ref is not null;

-- players ask for their balance back; the operator sends it (POST /api/admin/withdraw)
create table mine.withdraw_requests (
  id bigint generated by default as identity primary key,
  wallet text not null,
  amount_wei text not null,
  status text not null check (status in ('open', 'paid', 'cancelled')),
  created_at bigint not null,
  done_at bigint,
  tx text
);
create index withdraw_requests_open on mine.withdraw_requests (wallet) where status = 'open';

-- program jobs pay the miners who settled them: the pool part of the charge, split by wallet
create table mine.earnings (
  month text not null,
  wallet text not null,
  order_id text not null,
  task bigint not null,
  amount_wei text not null,
  at bigint not null,
  ref text
);
create index earnings_by_month on mine.earnings (month, wallet);
create unique index earnings_ref on mine.earnings (ref) where ref is not null;

-- a closed month's payout, committed to by a Merkle root
create table mine.snapshots (
  month text primary key,
  pool_wei text not null,
  root text not null,
  total_points double precision not null,
  wallets integer not null,
  created_at bigint not null
);
create table mine.snapshot_claims (
  month text not null references mine.snapshots (month),
  wallet text not null,
  points double precision not null,
  amount_wei text not null,
  proof text not null,
  primary key (month, wallet)
);
create index snapshot_claims_by_wallet on mine.snapshot_claims (wallet);

-- a wallet's FlyStaking balance on a UTC day: the lowest sample sets that day's multiplier
create table mine.stake_samples (
  wallet text not null,
  day text not null,
  staked_wei text not null,
  last_wei text not null,
  sampled_at bigint not null,
  primary key (wallet, day)
);

-- Fly Roulette
create table mine.roulette_commits (
  id text primary key,
  wallet text not null,
  server_seed text not null,
  hash text not null,
  created_at bigint not null,
  used integer not null default 0
);
create index roulette_commits_by_wallet on mine.roulette_commits (wallet, created_at);
create table mine.roulette_games (
  id text primary key,
  wallet text not null,
  flies integer not null,
  pick integer not null,
  stake_wei text not null,
  payout_wei text not null,
  edge double precision not null,
  commit_hash text not null,
  server_seed text not null,
  client_seed text not null,
  names text not null,
  status text not null check (status in ('live', 'done', 'void')),
  winner integer,
  events integer not null default 0,
  created_at bigint not null,
  done_at bigint
);
create index roulette_games_by_wallet on mine.roulette_games (wallet, created_at);
create index roulette_games_live on mine.roulette_games (status) where status = 'live';
create index roulette_games_done on mine.roulette_games (done_at) where status = 'done';
create table mine.roulette_events (
  game text not null,
  seq integer not null,
  event text not null,
  primary key (game, seq)
);
create table mine.roulette_terms (
  wallet text primary key,
  version integer not null,
  accepted_at bigint not null
);

-- FlightPass: a pass's balance is the ledger under pass:<token id>
create table mine.flightpass (
  id bigint primary key,
  settings text not null,
  last_bet_at bigint,
  updated_at bigint not null
);
create table mine.flightpass_withdrawals (
  id bigint generated by default as identity primary key,
  pass bigint not null,
  wallet text not null,
  amount_wei text not null,
  fee_wei text not null,
  status text not null check (status in ('open', 'paid', 'cancelled')),
  created_at bigint not null,
  done_at bigint,
  tx text,
  sending_at bigint,
  error text
);
create index flightpass_withdrawals_open on mine.flightpass_withdrawals (pass) where status = 'open';
create table mine.flightpass_days (
  pass bigint not null,
  day text not null,
  wallet text not null,
  broken integer not null default 0,
  samples integer not null,
  primary key (pass, day)
);
create index flightpass_days_by_wallet on mine.flightpass_days (day, wallet) where broken = 0;
create table mine.flightpass_owners (
  pass bigint primary key,
  wallet text not null,
  at bigint not null
);
create index flightpass_owners_by_wallet on mine.flightpass_owners (wallet);

-- Fly Slots
create table mine.slots_commits (
  id text primary key,
  wallet text not null,
  server_seed text not null,
  hash text not null,
  created_at bigint not null,
  used integer not null default 0
);
create index slots_commits_by_wallet on mine.slots_commits (wallet, created_at);
create table mine.slots_spins (
  id text primary key,
  wallet text not null,
  stake_wei text not null,
  mult integer not null,
  payout_wei text not null,
  stops text not null,
  symbols text not null,
  commit_hash text not null,
  server_seed text not null,
  client_seed text not null,
  created_at bigint not null
);
create index slots_spins_by_wallet on mine.slots_spins (wallet, created_at);
create index slots_spins_by_time on mine.slots_spins (created_at);

-- Fly Race
create table mine.race_commits (
  id text primary key,
  wallet text not null,
  server_seed text not null,
  hash text not null,
  created_at bigint not null,
  used integer not null default 0
);
create index race_commits_by_wallet on mine.race_commits (wallet, created_at);
create table mine.race_games (
  id text primary key,
  wallet text not null,
  bet text not null check (bet in ('win', 'podium')),
  pick integer not null,
  stake_wei text not null,
  payout_wei text not null,
  edge double precision not null,
  commit_hash text not null,
  server_seed text not null,
  client_seed text not null,
  names text not null,
  status text not null check (status in ('live', 'done', 'void')),
  won integer,
  finish text,
  events integer not null default 0,
  created_at bigint not null,
  done_at bigint
);
create index race_games_by_wallet on mine.race_games (wallet, created_at);
create index race_games_live on mine.race_games (status) where status = 'live';
create index race_games_done on mine.race_games (done_at) where status = 'done';
create table mine.race_events (
  race text not null,
  seq integer not null,
  event text not null,
  primary key (race, seq)
);
